-- { "model_path", tier }
-- tier 1 = tiny (~6-18 HU)    tier 2 = small (~18-35 HU)    tier 3 = medium (~35-65 HU)
-- tier 4 = large (~65-110 HU) tier 5 = very large (~110+ HU)
-- Duplicates are intentional — they bias smaller props to appear more often at round start.

return {
	-- Tier 1
	{ "models/props_junk/popcan01a.mdl",                  1 },
	{ "models/props_junk/popcan01a.mdl",                  1 },
	{ "models/props_junk/popcan01a.mdl",                  1 },
	{ "models/props_junk/garbage_metalcan001a.mdl",       1 },
	{ "models/props_junk/garbage_metalcan001a.mdl",       1 },
	{ "models/props_junk/watermelon01.mdl",               1 },
	{ "models/props_junk/watermelon01.mdl",               1 },
	{ "models/props_c17/doll01.mdl",                      1 },
	{ "models/props_c17/doll01.mdl",                      1 },
	{ "models/props_c17/metalpot001a.mdl",                1 },
	{ "models/props_c17/metalpot002a.mdl",                1 },
	{ "models/props_c17/canister01a.mdl",                 1 },
	{ "models/props_c17/canister02a.mdl",                 1 },
	{ "models/props_c17/canister_propane01a.mdl",         1 },
	{ "models/props_c17/tools_wrench01a.mdl",             1 },
	{ "models/props_c17/tools_pliers01a.mdl",             1 },
	{ "models/props_c17/clock01.mdl",                     1 },
	{ "models/props_c17/computer01_keyboard.mdl",         1 },
	{ "models/props_c17/cashregister01a.mdl",             1 },
	{ "models/props_c17/briefcase001a.mdl",               1 },
	{ "models/props_c17/suitcase001a.mdl",                1 },
	{ "models/props_c17/suitcase_passenger_physics.mdl",  1 },
	{ "models/props_lab/huladoll.mdl",                    1 },
	{ "models/props_lab/huladoll.mdl",                    1 },
	{ "models/props_lab/jar01a.mdl",                      1 },
	{ "models/props_lab/jar01b.mdl",                      1 },
	{ "models/props_lab/citizenradio.mdl",                1 },
	{ "models/props_lab/harddrive01.mdl",                 1 },
	{ "models/props_lab/harddrive02.mdl",                 1 },
	{ "models/props_lab/binderblue.mdl",                  1 },
	{ "models/props_lab/bindergreen.mdl",                 1 },
	{ "models/props_lab/desklamp01.mdl",                  1 },
	{ "models/props_lab/hev_case.mdl",                    1 },
	{ "models/props_interiors/pot01a.mdl",                1 },
	{ "models/props_interiors/pot02a.mdl",                1 },

	-- Tier 2
	{ "models/props_lab/box01a.mdl",                           2 },
	{ "models/props_lab/box01b.mdl",                           2 },
	{ "models/props_junk/cardboard_box004a.mdl",               2 },
	{ "models/props_junk/cardboard_box004a.mdl",               2 },
	{ "models/props_junk/wood_crate001a.mdl",                  2 },
	{ "models/props_junk/wood_crate001a.mdl",                  2 },
	{ "models/props_c17/bench01a.mdl",                         2 },
	{ "models/props_c17/chair_office01a.mdl",                  2 },
	{ "models/props_c17/chair_stool01a.mdl",                   2 },
	{ "models/props_c17/chair02a.mdl",                         2 },
	{ "models/props_c17/chair_kleiner03a.mdl",                 2 },
	{ "models/props_c17/furniturechair001a.mdl",               2 },
	{ "models/props_c17/furniturearmchair001a.mdl",            2 },
	{ "models/props_c17/tv_monitor01.mdl",                     2 },
	{ "models/props_c17/consolebox01a.mdl",                    2 },
	{ "models/props_c17/consolebox03a.mdl",                    2 },
	{ "models/props_c17/consolebox05a.mdl",                    2 },
	{ "models/props_c17/shelfunit01a.mdl",                     2 },
	{ "models/props_c17/gravestone001a.mdl",                   2 },
	{ "models/props_c17/gravestone002a.mdl",                   2 },
	{ "models/props_c17/gravestone003a.mdl",                   2 },
	{ "models/props_c17/gravestone004a.mdl",                   2 },
	{ "models/props_c17/gravestone_cross001a.mdl",             2 },
	{ "models/props_c17/gravestone_cross001b.mdl",             2 },
	{ "models/props_c17/playgroundslide01.mdl",                2 },
	{ "models/props_interiors/furniture_chair01a.mdl",         2 },
	{ "models/props_interiors/furniture_chair03a.mdl",         2 },
	{ "models/props_interiors/furniture_desk01a.mdl",          2 },
	{ "models/props_interiors/furniture_cabinetdrawer01a.mdl", 2 },
	{ "models/props_interiors/furniture_cabinetdrawer02a.mdl", 2 },
	{ "models/props_interiors/furniture_shelf01a.mdl",         2 },
	{ "models/props_interiors/furniture_vanity01a.mdl",        2 },
	{ "models/props_interiors/radiator01a.mdl",                2 },
	{ "models/props_interiors/sinkkitchen01a.mdl",             2 },
	{ "models/props_lab/cactus.mdl",                           2 },
	{ "models/props_lab/partsbin01.mdl",                       2 },
	{ "models/props_lab/monitor01a.mdl",                       2 },
	{ "models/props_lab/monitor01b.mdl",                       2 },
	{ "models/props_lab/monitor02.mdl",                        2 },
	{ "models/props_lab/filecabinet02.mdl",                    2 },
	{ "models/props_lab/cornerunit.mdl",                       2 },
	{ "models/props_lab/cornerunit2.mdl",                      2 },
	{ "models/props_lab/powerbox01a.mdl",                      2 },
	{ "models/props_lab/powerbox02a.mdl",                      2 },
	{ "models/props_lab/reciever01a.mdl",                      2 },
	{ "models/props_lab/plotter.mdl",                          2 },
	{ "models/props_lab/crematorcase.mdl",                     2 },

	-- Tier 3
	{ "models/props_c17/oildrum001.mdl",                  3 },
	{ "models/props_borealis/bluebarrel001.mdl",          3 },
	{ "models/props_c17/concrete_barrier001a.mdl",        3 },
	{ "models/props_c17/traffic_light001a.mdl",           3 },
	{ "models/props_c17/display_cooler01a.mdl",           3 },
	{ "models/props_c17/lockers001a.mdl",                 3 },
	{ "models/props_c17/gravestone_statue001a.mdl",       3 },
	{ "models/props_interiors/bathtub01a.mdl",            3 },
	{ "models/props_interiors/refrigerator01a.mdl",       3 },
	{ "models/props_interiors/vendingmachinesoda01a.mdl", 3 },
	{ "models/props_lab/lockers.mdl",                     3 },
	{ "models/props_lab/kennel_physics.mdl",              3 },
	{ "models/props_lab/servers.mdl",                     3 },
	{ "models/props_lab/generator.mdl",                   3 },
	{ "models/props_lab/generatorconsole.mdl",            3 },
	{ "models/props_lab/securitybank.mdl",                3 },
	{ "models/props_lab/reciever_cart.mdl",               3 },
	{ "models/props_lab/workspace001.mdl",                3 },
	{ "models/props_lab/workspace002.mdl",                3 },

	-- Tier 4
	{ "models/props_c17/furnituretable001a.mdl",          4 },
	{ "models/props_c17/furnituretable002a.mdl",          4 },
	{ "models/props_c17/furnituretable003a.mdl",          4 },
	{ "models/props_c17/furniturecouch001a.mdl",          4 },
	{ "models/props_c17/furniturecouch002a.mdl",          4 },
	{ "models/props_c17/furniturebed001a.mdl",            4 },
	{ "models/props_c17/furnituremattress001a.mdl",       4 },
	{ "models/props_c17/furniturefridge001a.mdl",         4 },
	{ "models/props_c17/furniturestove001a.mdl",          4 },
	{ "models/props_c17/furniturewashingmachine001a.mdl", 4 },
	{ "models/props_c17/furnituredresser001a.mdl",        4 },
	{ "models/props_c17/furniturebathtub001a.mdl",        4 },
	{ "models/props_c17/furniturecupboard001a.mdl",       4 },
	{ "models/props_c17/furnituredrawer001a.mdl",         4 },
	{ "models/props_c17/furnituredrawer002a.mdl",         4 },
	{ "models/props_c17/furnituredrawer003a.mdl",         4 },
	{ "models/props_c17/furnitureshelf001a.mdl",          4 },
	{ "models/props_c17/furnitureshelf002a.mdl",          4 },
	{ "models/props_c17/furnituretoilet001a.mdl",         4 },
	{ "models/props_c17/furniturefireplace001a.mdl",      4 },
	{ "models/props_c17/furnitureradiator001a.mdl",       4 },
	{ "models/props_c17/furnitureboiler001a.mdl",         4 },
	{ "models/props_c17/furnituresink001a.mdl",           4 },
	{ "models/props_interiors/furniture_couch01a.mdl",    4 },
	{ "models/props_interiors/furniture_couch02a.mdl",    4 },
	{ "models/props_lab/hev_machine.mdl",                 4 },
	{ "models/props_lab/bigrock.mdl",                     4 },

	-- Tier 5
	{ "models/props_c17/fountain_01.mdl",              5 },
	{ "models/props_c17/statue_horse.mdl",             5 },
	{ "models/props_c17/playground_carousel01.mdl",    5 },
	{ "models/props_c17/playground_swingset01.mdl",    5 },
	{ "models/props_c17/playground_jungle_gym01a.mdl", 5 },
	{ "models/props_junk/trashdumpster01a.mdl",        5 },
	{ "models/props_lab/scrapyarddumpster.mdl",        5 },
	{ "models/props_vehicles/van001a_physics.mdl",     5 },
	{ "models/props_vehicles/car003a_physics.mdl",     5 },
	{ "models/props_wasteland/cargo_container01.mdl",  5 },
}
